name: Build VANY ROM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Maximize Build Space Safely
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo apt-get clean
          df -h

      - name: Set up Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bisect-pp ccache flex bison gptfdisk gdisk build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig

      - name: Build ROM
        run: |
          source build/envsetup.sh
          lunch lineage_vany8-userdebug
          mka bacon -j$(nproc --all)
